
spring:
  application:
    name: api

server:
  port: 8051
  netty:
    reader-idle-time: 60000
    writer-idle-time: 60000


redis:
  mode: standalone  # standalone or sentinels or cluster
  master: mymaster
  db_num: 0  # local only (spring.profile=local)
  password :
  standalone:
    host: localhost
    port: 6379
  sentinels:
    host: 127.0.0.1, 127.0.0.2
    port: 26381, 26382
  cluster:
    host: node1, node2, node3, node4
    port: 6379, 6379, 6379, 6379
  timeout:
    cmdSec : 10  #sec